spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:postgresql://127.0.0.1:5432/db_test?characterEncoding=utf-8&useSSL=false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.demo.entity
  type-handlers-package: com.demo.handler
  mapper-locations: classpath:/mapper/*.xml

mb:
  type-handler-pkg: com.demo.entity

